/* TASK ACTION TYPES */
export const CREATE_TASK = "ACTION_CREATE_TASK";

/* DATA SERVICE */
export const SAGA_FETCH_DATA = "SAGA_FETCH_DATA";
export const SAGA_FETCH_START = "SAGA_FETCH_START";
export const SAGA_FETCH_SUCCESS = "SAGA_FETCH_SUCCESS";
export const SAGA_FETCH_FAILED = "SAGA_FETCH_FAILED";

export const SAGA_CREATE_TASK = "SAGA_CREATE_TASK";
export const SAGA_CREATE_START = "SAGA_CREATE_START";
export const SAGA_CREATE_SUCCESS = "SAGA_CREATE_SUCCESS";
export const SAGA_CREATE_FAILED = "SAGA_CREATE_FAILED";

export const SAGA_CLOSE_TASK = "SAGA_CLOSE_TASK";
export const SAGA_CLOSE_START = "SAGA_CLOSE_START";
export const SAGA_CLOSE_SUCCESS = "SAGA_CLOSE_SUCCESS";
export const SAGA_CLOSE_FAILED = "SAGA_CLOSE_FAILED";